import * as ImagePicker from 'expo-image-picker';
import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput } from 'react-native';
import { useRouter } from 'expo-router';
import { Eyebrow, Page, Title } from '@/components';
import { saveDraft } from '@/offline';
import { colors } from '@/theme';
import { createEncounter, prepareUploads, resumeUploads } from '@/uploads';

export default function Add(){const router=useRouter();const [title,setTitle]=useState('');const [story,setStory]=useState('');const [photos,setPhotos]=useState<ImagePicker.ImagePickerAsset[]>([]);const [saving,setSaving]=useState(false);const [progress,setProgress]=useState(0);useEffect(()=>{const handle=setTimeout(()=>void saveDraft('new-encounter',{title,story,photos:photos.map(p=>p.uri)}),400);return()=>clearTimeout(handle)},[title,story,photos]);async function pick(){const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsMultipleSelection:true,selectionLimit:200,quality:1,exif:false});if(!result.canceled)setPhotos(result.assets.slice(0,200))}async function save(){if(!title.trim())return Alert.alert('还差一个标题');setSaving(true);try{const encounter=await createEncounter({title:title.trim(),story});await prepareUploads(encounter.id,photos.map((photo,index)=>({uri:photo.uri,filename:photo.fileName??`photo-${index+1}.jpg`,mimeType:photo.mimeType??'image/jpeg',bytes:photo.fileSize??1})));await resumeUploads(encounter.id,(done,total)=>setProgress(total?Math.round(done/total*100):100));router.replace(`/encounter/${encounter.id}`);}catch(error){Alert.alert('暂时没有传完',`${error instanceof Error?error.message:'上传失败'}\n任务已保存在本机，下次可以继续。`);setSaving(false)}}return <Page><ScrollView keyboardShouldPersistTaps="handled"><Eyebrow>新的记录</Eyebrow><Title>这次发生了什么？</Title><Text style={s.label}>标题</Text><TextInput style={s.input} value={title} onChangeText={setTitle} placeholder="例如：下班后临时见面"/><Text style={s.label}>你的原话</Text><TextInput multiline style={[s.input,s.story]} value={story} onChangeText={setStory} placeholder="不用写得漂亮，AI 不会修改这些文字。"/><Pressable style={s.upload} onPress={pick} disabled={saving}><Text style={s.uploadTitle}>把照片都倒进来</Text><Text style={s.muted}>最多 200 张，原图都会保留</Text>{photos.length>0&&<Text style={s.count}>{photos.length} 张已选择</Text>}</Pressable><Pressable style={[s.button,saving&&s.disabled]} onPress={save} disabled={saving}><Text style={s.buttonText}>{saving?`正在上传 ${progress}%`:'保存并帮我整理'}</Text></Pressable></ScrollView></Page>}
const s=StyleSheet.create({label:{fontWeight:'700',marginTop:18,marginBottom:8,color:colors.ink},input:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.line,borderRadius:15,padding:14,fontSize:16},story:{minHeight:140,textAlignVertical:'top'},upload:{marginTop:20,borderWidth:2,borderStyle:'dashed',borderColor:'#d6c5af',borderRadius:22,padding:28,alignItems:'center',backgroundColor:'#fffaf1'},uploadTitle:{fontSize:17,fontWeight:'700',marginBottom:6},muted:{color:colors.muted},count:{color:colors.orangeDark,fontWeight:'700',marginTop:10},button:{backgroundColor:colors.orange,borderRadius:16,padding:16,alignItems:'center',marginVertical:20},disabled:{opacity:.65},buttonText:{color:'#fff',fontWeight:'700',fontSize:16}})
